### ISSUE TITLE
BUG: Row update doesn't ignore metadata properties

### ISSUE THREAD

**Issue by twistedstream** [twistedstream/google-sheets-table#18]
The following:

```typescript
const table = new GoogleSheetsTable({ ... });

// confirm we have an existing row
const { row } = await table.findRow((r) => r.id === "1234");
assert(row);
// => { id: "1234", name: "Bob S", _rowNumber = 2 }

// attempt to update the same row with some new data
await table.updateRow((r) => r.id === "1234", { name: "Bob Smith" });
```

Results the following error:
```text
Error: Table columns missing that exist as row properties: _rowNumber
  at rowToValues (/Users/peter/projects/twistedstream/skattlada/node_modules/google-sheets-table/dist/index.js:105:11)
  at /Users/peter/projects/twistedstream/skattlada/node_modules/google-sheets-table/dist/index.js:320:25
  at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This is because the `updateRow` method fetches an `extsingRow` first (which contains metadata property `_rowNumber`) and uses that [when calling](https://github.com/twistedstream/google-sheets-table/blob/0d519fd1881ebd2c5678c436c499adf7b45b59ad/src/GoogleSheetsTable.ts#L195) the `rowsToValues` helper function.

We need somehow remove the metadata properties from the `Row` (which really should be a `RowData`) before passing it to that function.

**Comment by twistedstream** [comment]
A different error now occurs:

```text
Error: There are constraint violations:
          A row already exists with id = 'BV7WxB63w1z9ReunhiZLOTFll'
              at enforceConstraints (/Users/peter/projects/twistedstream/skattlada/node_modules/google-sheets-table/dist/index.js:191:11)
              at /Users/peter/projects/twistedstream/skattlada/node_modules/google-sheets-table/dist/index.js:323:7
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

PR #19 inadvertently broke the constraint checking, which does not work with cloned row objects.
